//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALES_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Cities
    {
        public long Id { get; set; }
        public string CityName { get; set; }
        public long StateId { get; set; }
    
        public virtual TBL_States TBL_States { get; set; }
    }
}
